name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt install gcc-arm-none-eabi

    - name: Build
      run: make

    - uses: actions/upload-artifact@v4
      name: Upload artifacts
      with:
        name: Car
        path: |
          build/Car.hex
          build/Car.bin
